# Generated by Django 4.1.3 on 2022-12-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Iname', models.CharField(max_length=50)),
                ('Itype', models.CharField(choices=[('Dairy', 'Dairy'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Speces', 'Speces'), ('Nuts and Oil', 'Nuts and Oil Seeds'), ('Lentils', 'Lentils'), ('Cereals', 'Cereals'), ('Flours', 'Flours'), ('Grains', 'Grains'), ('Meat', 'Meat'), ('Pantry', 'Pantry')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rname', models.CharField(max_length=100)),
                ('Rimg', models.ImageField(upload_to='photos')),
                ('Rdesc', models.TextField()),
                ('Rtype', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Meals', 'Meals')], max_length=20)),
                ('Iname', models.ManyToManyField(to='home.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Nutritionalvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.CharField(max_length=10)),
                ('fats', models.CharField(max_length=10)),
                ('protien', models.CharField(max_length=10)),
                ('carbs', models.CharField(max_length=10)),
                ('Rname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.recipes')),
            ],
        ),
    ]
