# Generated by Django 4.1.3 on 2022-12-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionalvals',
            name='NRname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Rimg',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
