# Generated by Django 4.1.3 on 2022-12-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_nutritionalvals_nrname_alter_recipes_rimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='Iname',
            new_name='ingredientname',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='Iname',
            new_name='ingredientname',
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='Itype',
            field=models.CharField(choices=[('Dairy', 'Dairy'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Speces', ''), ('Nuts and Oil', 'Nuts and Oil Seeds'), ('Lentils', 'Lentils'), ('Cereals', 'Cereals'), ('Flours', 'Flours'), ('Grains', 'Grains'), ('Meat', 'Meat'), ('Pantry', 'Pantry')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Rtype',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Meals', 'Meals'), ('Dessert', 'Dessert')], max_length=20),
        ),
    ]
